### ISSUE TITLE
Websocket error with > 2 accessories

### ISSUE THREAD

**Issue by zellunit** [oznu/homebridge-unifi-occupancy-sensor#37]
i initially got my occupancy sensor working with two accessories that map to each of myself and my wife's devices for our own presence in our home. but when we tried to add another accessory for another family member there is an error. every time i reboot homebridge (running on hoobs) with the new config, it starts to boot up but i get a websocket error below and my entire system crashes. this includes all modules not just occupancy and is very disruptive. my guess is there is too much contention for the socket with 3 accessories trying to connect? is there a more graceful way this can softly error or retry? see below.

6/27/2021, 9:04:14 AM Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (/home/hoobs/.hoobs/node_modules/unifi-events/node_modules/ws/lib/websocket.js:367:19)
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/unifi-events/index.js:90:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

also i know i can put multiple devices on the same "accessory" but that defeats the purpose of knowing who is in the home not just "is someone" in the home. is there also a better way to configure this that accomplishes what i am looking to do?

any ideas would be hugely appreciated. thank you so much.

**Comment by zellunit** [comment]
@oznu : just wondering if anyone else has tried > 2 accessories. i thought maybe it was the weak throughput of my tiny hoobs so i got a fresh mac mini + homebridge and same thing happens. 1-2 accessories are fine. the moment you expand to 3 or more it gives the same error. any ideas?
